### ISSUE TITLE
多说现在还有人维护吗？

### ISSUE THREAD

**Issue by jerrybendy** [duoshuo/duoshuo-wordpress#4]
看不到多说更新了，官方论坛也充满了垃圾信息，BUG 一直无人修复，是不是准备放弃了？

**Comment by JiaJiaJiang** [comment]
别说出来

**Comment by jerrybendy** [comment]
@JiaJiaJiang 我去，在这里都能看到你 :joy:

话说现在国内还有好用的评论吗？多说已经是非常好的了，只是一些很纠结的 BUG 一直没人修复。 国外的 Disqus 已经连续被墙了几个月了

**Comment by Ma63d** [comment]
我也想问啊，而且现在多说的微信登录不行了，而我的站点的多说后台是绑定在微信上的，现在多说的微信登录不了，直接导致我连多说后台都进不去

**Comment by JiaJiaJiang** [comment]
@jerrybendy 你看我们在这说这个都没官方来回复，还能是怎么样。。。其它评论我也没找到什么速度快又不用备案的国内评论系统

**Comment by jerrybendy** [comment]
@JiaJiaJiang  好吧。。最近看到disqus 开放了 create 接口，虽然还是测试版本，但未尝不可以尝试自己实现一个 disqus ，在后台调用它的接口。不知道有没有这一方面现成的开源项目

**Comment by i2000s** [comment]
@jerrybendy 他们即使提供了接口恐怕也会被墙吧？接口信息还是 要传过去。

**Comment by jerrybendy** [comment]
@i2000s  如果是使用接口就不必担心被墙了，自己搭建反向代理就是。但是试了下他们的接口，通过接口创建评论还是不现实的，所有的评论都变成自言自语了。。。。😔

**Comment by i2000s** [comment]
@jerrybendy 好像JiaThis也有评论栏功能吧。完全转过去算了，虽然他家不提供https支持。

**Comment by jerrybendy** [comment]
@i2000s  不提供 https 就算了，不考虑。我现在又直接切到 Disqus 了，来回切了好几次，多说体验太差了，还是 Disqus 好些。至于有些人没翻墙看到不到评论，只能不管了～

**Comment by i2000s** [comment]
@jerrybendy 我是从外网转到内网的，还是希望 有个不错的插件可用，别给自己找麻烦了。好像畅言可用，不过需要手机号才能注册，我没手机，所以也没办法。期望能提供些其他选择。谢谢。

**Comment by jerrybendy** [comment]
@i2000s  不用畅言，各种不好用，而且畅言名不符实，各种无法“畅言”
